### PR TITLE
[nginx] Open OpenSearch endpoint at "/data"

### PR DESCRIPTION
**Pull request by zhquan**
This commit opens the OpenSearch endpoint at `/data`.

### CODE REVIEW

**Review by sduenas — COMMENTED** [review]
I'm not against this PR but to open to everybody the access to OpenSearch is a bit dangerous. We should know for sure that the security configuration and roles work before approving this.

**Comment by zhquan** [comment]
The users can only see their own indexes, aliases, and index patterns managed by the roles of OpenSearch. The users will have the same access as `dev tools` (OpenSearch Dashboards).

**Review by sduenas — CHANGES_REQUESTED** [review]
Can we have an option so the '/data' is not exposed by default?

**Comment by jjmerchante** [comment]
The changes requested by @sduenas are completed. Only instances with `http_rest_api` to true have `/data` open.

LGTM

**Pull request merged**
